[target.aarch64-linux-android]
ar = "/opt/homebrew/Caskroom/android-ndk/27c/AndroidNDK12479018.app/Contents/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/opt/homebrew/Caskroom/android-ndk/27c/AndroidNDK12479018.app/Contents/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-feature=+crt-static"
]
